### ISSUE TITLE
 Identity Statement Question Request

### ISSUE THREAD

**Issue by kaylia-rainierathletes** [rainier-athletes-v2/frontend#143]
name: Identity Statement Question
about: dropdown question where mentors can update on where they are in the Identity Statement Process
title: "Identity Statement"
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A drop down question added to the portal. This questions should only be viewable on Salesforce, and not be pushed to Basecamp

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot below with question and answer options
![Identity Statement Request](https://user-images.githubusercontent.com/74576171/99329405-fe9b5280-2832-11eb-998b-83435fc9ff22.PNG)

**Comment by TCW417** [comment]
@kaylia-rainierathletes : Do you want the pick list values to include the "Tier N:" text? For example,
Tier 1: Values Tables vs just "Values Tables"
Also, the Tier 3 text is pretty long which will impact the width of the dropdown. Could we shorten it to "All Complete"?

**Comment by kaylia-rainierathletes** [comment]
@TCW417 Yes, please include the "Tier N"
For Tier 3  What about "Values and Questions Complete" Or is that still too long?

**Comment by TCW417** [comment]
That should be fine.  I'll create a pick list field in SF named... "Identify Statement Response"  ?  Or give me another name.

**Comment by kaylia-rainierathletes** [comment]
@TCW417 let's go with "Identity Statement Status" 
I'll include SF name in the future!

**Comment by TCW417** [comment]
Willco. Thanks.

**Comment by TCW417** [comment]
Merged with staging for review. Deployed stating to prod instances.

**Comment by kaylia-rainierathletes** [comment]
This looks great! We had mentors fill this in on the reports on Friday and over the weekend! Easy to find out which tier mentors are on the SF side as well.  Looks good!

**Comment by TCW417** [comment]
@kaylia-rainierathletes confirmed fix is working. Merged with master and deployed to prod.
