### ISSUE TITLE
 Access to Synopsis Reports

### ISSUE THREAD

**Issue by kaylia-rainierathletes** [rainier-athletes-v2/frontend#144]
**Is your feature request related to a problem? Please describe.**
Mentors who miss a week of reporting are going back and filling in both the previous week and the current week synopsis reports. This is creating confusion especially if one describes the mentor and student meeting one week, and not for another. 

**Describe the solution you'd like**
I would like for the mentors to only have access to the most recent synopsis report created

**Describe alternatives you've considered**

**Additional context**
Screenshot below of mentor view on portal. 
![Synopsis Report Access](https://user-images.githubusercontent.com/74576171/99330369-761db180-2834-11eb-90fd-1deb4670bef3.PNG)

**Comment by kaylia-rainierathletes** [comment]
How do I assign the enhancement label on these requests?

**Comment by jlema** [comment]
@kaylia-rainierathletes You click on the cog icon next to Labels then click on the enhancement label.
![image](https://user-images.githubusercontent.com/9736891/99348484-8d699880-284e-11eb-905c-d865581c5cc7.png)

**Comment by TCW417** [comment]
This change has been released to staging and master branches and deployed.
