### ISSUE TITLE
Error Message adding new contact to mentor community

### ISSUE THREAD

**Issue by kaylia-rainierathletes** [rainier-athletes-v2/frontend#150]
**Describe the bug**
Adding a new mentor to the mentor community for portal access. I received an error message about checking a role. The mentor role is checked on her contact info. 

**To Reproduce**
1. Go to 'Julie Honn' double check "mentor role" is checked
2. Click on 'down arrow next to "new donation," then click  "enable customer user"
3. Scroll down to "Profile" click on down arrow and then click on "mentor community user"
4. Press save, then press ok. Error message pops up 

**Expected behavior**
Expect for the save mentor as community user and a link to create a password is email to their email
![Role Checked](https://user-images.githubusercontent.com/74576171/101540516-fd060b80-3954-11eb-85ca-e7fa3b03d5ba.PNG)
![Error](https://user-images.githubusercontent.com/74576171/101540522-fd060b80-3954-11eb-8ebd-5d9725cd5917.PNG)

.

**Screenshots**

**Desktop environment (please complete the following information):**
 - OS and version: [e.g. Windows 10]: 
 - Browser and version [e.g. Chrome 87]:

**Additional context**

**Comment by TCW417** [comment]
@kaylia-rainierathletes This is a Salesforce issue, not a portal issue. I'll look into it but it's outside the scope of the mentor app project. The role the error message is talking about most likely isn't a Rainier Athletes Role but a Salesforce role that's missing somewhere.

**Comment by TCW417** [comment]
@kaylia-rainierathletes I don't see Julie in the users list (Salesforce, setup, users). As a mentor she needs to be created there as she's not simply a Salesforce contact but a user.

**Comment by kaylia-rainierathletes** [comment]
Yes, I was trying update Julie's contact to a mentor user but then I got the error when doing so. I will reach out to SF. Thanks!
