### ISSUE TITLE
Summer Portal Updates

### ISSUE THREAD

**Issue by kaylia-rainierathletes** [rainier-athletes-v2/frontend#151]
**Is your feature request related to a problem? Please describe.**
We are ready to update the synopsis reports for the summer.

**Describe the solution you'd like**
- Update the What's Been Happening Text box to optional
- Remove Online School Update 
- Remove Additional  Team Comments

**Comment by TCW417** [comment]
I removed the online school update and additional team comments blocks. I don't see in the code where the what's been happening block is required. As of just now haven't done anything with that. Deploying feature branch to verify.

**Comment by TCW417** [comment]
I've deployed my issue 151 feature branch to heroku. Two text blocks removed. @kaylia-rainierathletes : Not sure what you're intention is concerning making what's been happening optional. It's already optional from a verification standpoint. Do you mean adding "(Optional)" to the label?

Feature branch name is Issue-151-summer-portal-updates (for my benefit).

**Comment by kaylia-rainierathletes** [comment]
Great- thank you! 

If it's already optional from a verification standpoint that is what we want. No need to add (Optional) to the label This can be closed out!
