### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kbnaik13** [rainier-athletes-v2/frontend#155]
**Describe the bug**
Synopsis reports have been getting posted to their sibling’s basecamp pages after portal is filled out by staff. For the example screenshot below, the two students involved are Isaias Solares-Xona and Jacob Corrtes-Xona. The report was filled out for Jacob and the mentor is able to click the submit button to core community button on portal. However instead of posting to Jacob’s basecamp the report posts to Isaias.

**To Reproduce**
1. Go to https://portal2.rainierathletes.org/. 
2. Click on blue ‘Sign in’ in top right corner
3. Enter in username and password for Portal
4. Click ‘Allow’ when Salesforce screen pops up and prompts
5. Click ‘Yes, I’ll allow access’ when Basecamp screen prompts
6. Click student from left panel and then click ‘Edit’
7. Fill out synopsis report and then click green ‘Submit’ button to core community
8. Check student’s basecamp to see if report was posted to correct student
9. Error: Report is posted to sibling’s basecamp instead of the correct

**Expected behavior**
The report is posted to the correct student’s salesforce page

**Screenshots**
<img width="968" alt="Screen Shot 2021-12-07 at 4 16 48 PM" src="https://user-images.githubusercontent.com/95324334/145313010-c4daad72-f7e8-457f-8057-b88f0c22f7c5.png">

**Desktop environment (please complete the following information):**
 - OS and version: [e.g. Windows 10]: 
 - Browser and version [e.g. Chrome 87]:

**Additional context**
This only seems to occur when staff posts reports. Staff do have access to every students' Basecamp team

**Comment by TCW417** [comment]
It's very possible this issue will be corrected after the fix for #154 is released (which it is as of now).  Please check and comment either way. If it's fixed you can close the issue.

**Comment by TCW417** [comment]
@kbnaik13 Can you check and see if this is still an issue with the currently deployed app?

**Comment by kbnaik13** [comment]
@TCW417 this issue has been fixed, thanks so much!
